### ISSUE TITLE
`typeTerm'`'s `Sig'` case doesn't handle dependency

### ISSUE THREAD

**Issue by rokopt** [anomanetwork/juvix#853]
The `Sig'` case of `typeTerm'` currently reads:

```haskell
    IR.Sig' π a b _ -> do
      requireZero σ
      void $ requireStar ty
      a' <- typeTerm' a ann
      b' <- typeTerm' b ann
      pure $ Typed.Sig π a' b' ann
```

That doesn't handle the possibility that the second type might depend on the first.  It should be enhanced to do so.

**Comment by andy-morris** [comment]
oh yeah! this is one of the things we noticed last week so it's in #852. we can separate it out into a separate PR though since it's not exactly "a minor cleanup"

**Comment by rokopt** [comment]
> oh yeah! this is one of the things we noticed last week so it's in #852. we can separate it out into a separate PR though since it's not exactly "a minor cleanup" if that would be better

Oh!  I see we wrote identical fixes, so that's good.  :)   I wrote some tests in https://github.com/anomanetwork/juvix/commit/0c21f12300230bead32346a3340128f7e50a7a3b , but what I haven't managed to do yet is find a test that fails on the _old_ code which the new code fixes.
